"""Tests for ProtSeqIO fasta helper module."""

from protseqspark.ProtSeq import ProteinSequence
from protseqspark import ProtSeqIO

proteome1_seqs = [
    ProteinSequence(
        "Q6F1Z5",
        "RS10",
        "MESFL",
        "MAEQKMRIKLKGYDHAIIDQSILKIIEAAEGTGAKVRGPIPLPTDKQVITILRAVHKYKDSREQFEMRTHKRLLEILNPTPTTMDVLKRVQLPSGVDIEIKL"),
    ProteinSequence(
        "Q6F0Y1",
        "TSAD",
        "MESFL",
        "MKILAIESSCDEFSISIIDDGKILTNIISSQIDQHVNFGGVVPELAARLHLENISWVIKSALESSNTKIEEIDHVAYTEKPGLIGSLIIGKLVAETIASYIDKPLMPLHHIEGHIYGASIENEFVYPVLAMVVSGGHTQIEIVNSPNEFEVIGATLDDAIGECYDKVARVMGLGYPGGPKIDKLAQKGNKEAFIFPISKNDDSYDFSYSGLKTAVINIIHNLTQKGEEIPVADIAASFQYAATKIVEKKLEKAIIQFKPKTLTVAGGVSANSEIRNIIMSLGKKYNITNTFVPKMEYCTDNAAMIAKLAYEKLKSSN"),
    ProteinSequence(
        "Q6F1W7",
        "RPOA",
        "MESFL",
        "MKQFNKPEFGIVKESPNKFYGKFEAAPLERGFAVTLGNALRRTLLSSTPGASVFAIKIAGAQHEFTSISGIEENVTRIVLNVKKLILRIDSAIYNDDETVELKVGTSTIGPVTAGSLVLPAGVEVLNKDLVIANVAEGGNLDLVLYAKNSRGYKTFKENKELKDVVPGMITIDSNYSPIIKVAYGSTPINLGKAQDFEKLILEVETDGSILASDAVSLASKILISHFDVFTTLAEEVEEVAIMGVETVEEKELDKPVEELEFTQRSLNCLKRAGISTLRELVSKTEDEIQDIRNLGRKSLKEIKDKVAALELTFKQN"),
]


class TestFastaHelper:
    def test_readFastaFileCorrectly(self):
        seqs = list(ProtSeqIO.readSequencesFromFasta(
            "Tests/Fasta/proteome1.fasta"
        ))
        assert len(proteome1_seqs) == len(seqs)
        assert proteome1_seqs[0] == seqs[0]
        assert proteome1_seqs[1] == seqs[1]
        assert proteome1_seqs[2] == seqs[2]
